language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
  - secure: fQvhSsxCY4SrOZWdoRhfmgvnECITXVsNyC1ozzMZvmpb0SJEg1AdQ+c0tlFM5w0GfshALkTjb0kGRWK+9HTNZNLo/6Fd6kTj829z6NC9WYxBYM7pPDeOWrDR/rlIsyR/PuSV/VHDDEa9TWTrh14bFbNAiLetkTLpcqmeoozq63HmAzoJJWoGtafkgglYsUfd0aPzA1iDbUMB5RJKuFIl6LuhYIYT7ZJxIHW/RHkH2ksGR7IZn97BAGN92d1cZSe8FD2J/1x8yPvx6PBJGveL2qwllpdjUDdiJcueen9pKNeE0nrseV8JwjotX5lUF13n9B91FggRsoMHKQjcVuSbx55svIapB2/phiuE+N/KpBb/KTSjrT5bVltqPlHtfnMutDTBFlBHqmdCg6P4zGNL0a8EbaMxBIRl+ue+NZtBNOun2kaSf8VhyhdhQMB6F6NL6uddRW8FID6Kjs6OlatJfDgm13xCPlqNN6EgGbAsf9EVWHt1qmerJrcmZl/lLiCNY3HtX5HwaOMHPRfKjlV0jDcHlvX14W0N8X6Bhn7avVSQVl08KHA6ZF0kuqKTsqoPpFwBKNuDgLvc7y53F428Jr2oEK4BLQC5lAhzjiGHi5d2NBJPJ069wPJogr6rlUI+yv/XOyMDw3jpsd9wAlhTm30S6OqyH8/Qk9j0V4waYSY=
  - secure: QWYH7BSssNPl2zV7Ss0RrJoW1GT3lk8KJijjp2bh1GI9viREOuvaWL0naqtQxWx1y6XS6HoTy9po0JR95BDCS1X1XrVP+MMyJGaV+AwoGjbbiST8jPlV4lgjbJd74Ydo3nbpPLx3j/Qm8XrdJHSW5Y/qF0CcZaj/ExeiQKwm74sYDUJuypE15FYlcxjFJGQVZTLK+g0TZhqOhDEEdD67bFZGx8t1rWiaoHrZacgbahpFBD//pMhrRZdR3bjoHnjXaMsvEmSUxuJ7DyBqCh2603HxSrGASg8l9ZDKsBiLPKfISsZW8W23zl1FCaeb9j0zFz1421laszsyLcWgpl5vnbh/cTxvl0A7d0qjg36SOBztIklXy2oFJjjrHWtYiqfNkFXsvteHWj105n5+nxrxl5r590OUCadjSDy+Vna8pdurRiHvENjNG/w+z73pswe7/FrN0wy1x7EiKQ+vMYpdXn4+BFrI1PsDUajdm7X9HqUm8aNrkhISw6A5LljnHW+z3Ok0NiPZG2U+9NK95dSrC/i8maSDqoCoEYYBsjXe2jCbH/ncjh0BaMs/+uM0Rxv2zhZ3LayaxHGJyRISN4cxLc8k3GUKu6+MvfNxO5jlwESFCr2uGtvcF8OpMpgExaBog6kOs9AkEvuJ1n5xhDe/Pc+o+h+tHm8CpD/MT3Qh55g=

install: 
  - pip install -r requirements-build.txt

script:
  - nb test

jobs:
  include:
  - stage: deploy
    python: 3.6
    script: nb pypi
