dist: xenial
sudo: true
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
env:
  global:
  - secure: R6ch4fcr3D99ILWkxFl+O7YlbblDeKPTQhBcUQLk7dUV77zhUI75I0sUDMucvwZXJYJR7dptVUOqTcN44hR6IFr+adoYKT6CcdmofKgLqKRSS1uWVx+KYLq7H9srMYpwQl3FjhwMoR+KqVOi/gCyXcUBIECUzmMVfRY1QUG1hQ/rra5TI96LuBSuu/o1EREITzfezIurqBQs5BZuE+rD1USQ2EIcBQHCLfibwpqgcRTI/FkdpaIRDtUr9V7mw2380JVlzEIJSsfSaqd5VGuENlJln6XzyUuGfol1LZ4u/ismmttT/tP9PIhVSS9AP2ftWGdjkROkQ8ytMO0xEtymbRY3N1Yzx9FCbqEMU3RXX3yzjKy76m7Z0LFXpw0AMys2eieeTlJ73OYy8iaUWjA61ZMt4skc4xDW1wOJjmXE2jDAR5W+tdaPaAQLvjWgYha3OwZiv9g074Bj+SSQ86/AbiKFS6wC2WFetvC+zq4kyLTzeLbfr++YPLwKURcMRHOeT2TKhtWI8O+CUkUCTu3vLkfJ+NJpaTYuz+Bx0hzh7FeplG9g174fLoG1Ef0huDwYxCb7MAg0rdA0zM3yfIobUuTlFeqBRobwMckCxqLe3BnWeQjw83B+mEGbIPcOIIlpczFc2LvVFDy0Pnwp/SbKuIMznzPQQj6XQXvwMFF3x+o=
  - secure: Iq6rbtp+4YfrnXIPYIF/v2ErB5vv3bzUlh8CWcDOcWPxjZHHRmKnS38NH1356HuqeEz0CY5lxE1GQkTc0rFx9K34bGR4UYS9F4IoD2k8C4GyUHTq1ytWdtJryBk7q+w6qKBKD9Cd6swDlU0W4SZ3CEX2tkAw5moB/OTgRbIjDfBBtEPxvn3U2Yr/LfkV7OTHTIL8yjxtHq2S1zZC4Rqva5oiRoi91at6H4tb/t+DYNvyXFh/NnzXXStfy96TMn2bPLhuRfUqb3fySeJOkaXZ8YUQt/QBANdmnLpmPBuxEiT6Ji4WehAn+lB34Fv3sma4dnetltn3eJLTMNjianyORr2N3PxU32F1/JtUZlhVuzET5bLEgFMjGjODg5YXvT0/m5l0Vw8/O56F0DfWlyeo1o6SaFG2yCwOSPRsLok5kCB9BZKv5einA58tMBWYqOB0o9QZgx1CjYHh9QUe0ABiMAyIrJNUEqhVkXpGtL+zUKshj/3h5tsdRpPAj/eQfnbql4ED5w+NuZJiP8KrufXmY0fK3ftqD0qYNGpY5XEyhJiXSAXE98/PTj9fBLnDami89l36rNBGSGb5wiBl4ANsMBykOD6LBdnrNiOOJb8lzsbALYJ5lw5DAJBx6CRh3j6RgU60sul28cZb3SUn7emkTuh4vE/0Rz90nGiroCJbr6o=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
script:
- nb test
jobs:
  include:
  - stage: deploy
    python: 3.7
    script: nb pypi
